name: Test javascript

on: push

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  js-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Setup Yarn
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: yarn install

      - name: Test
        id: test
        if: ${{ success() }}
        run: yarn test

      - name: Upload coverage to OtterWise
        if: >
          ${{ vars.OTTERWISE_ENABLED == 'true' && 
              steps.test.outcome != 'skipped' && 
              steps.test.outcome != 'cancelled' }}
        uses: getOtterWise/github-action@v1
        with:
          token: ${{ secrets.OTTERWISE_TOKEN }}

      - name: Upload coverage to Coveralls
        if: >
          ${{ vars.COVERALLS_ENABLED == 'true' &&  
              steps.test.outcome != 'skipped' && 
              steps.test.outcome != 'cancelled' }}
        uses: coverallsapp/github-action@v2
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          format: lcov
          file: ./coverage/lcov.info

      - name: Upload coverage to Codecov
        if: >
          ${{ vars.CODECOV_ENABLED == 'true' &&
              steps.test.outcome != 'skipped' && 
              steps.test.outcome != 'cancelled' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: >
          ${{ vars.CODECOV_ENABLED == 'true' && 
              steps.test.outcome != 'skipped' && 
              steps.test.outcome != 'cancelled' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
